

CREATE DATABASE HoaYeuThuong
GO
USE HoaYeuThuong
GO
CREATE TABLE NGUYENLIEU
(
	MaNL INT NOT NULL IDENTITY(1,1),
	MaLoai INT NOT NULL, --Foreign key
	TenNL NVARCHAR(40),
	YNghia NVARCHAR(40),
	DonViTinh NVARCHAR(10),
	DonGiaNL MONEY,
	SoLuongKHO INT,
	SoLuongToiThieu INT
	PRIMARY KEY (MaNL)
	/*BS Foreign key cho MaLoai*/
)
GO
CREATE TABLE SANPHAM_NGUYENLIEU
(
	MaSP INT NOT NULL,
	MaNL INT NOT NULL,
	SoLuongNL INT,
	PRIMARY KEY (MaSP, MaNL),
	CONSTRAINT FK_SPNL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
	/*BS Foreign key cho MaSP */
)
GO
CREATE TABLE CUAHANG
(
	MaCH INT IDENTITY(1,1),
	TenCH NVARCHAR(40),
	SdtCH CHAR(10),
	DiaChi NVARCHAR(40),
	ChuThichCH NVARCHAR(50),
	PRIMARY KEY (MaCH)
)
GO
CREATE TABLE SOLUONG_CH
(
	MaCH INT NOT NULL,
	MaNL INT NOT NULL,
	SoLuongCH INT,
	PRIMARY KEY (MaCH, MaNL),
	CONSTRAINT FK_CH FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH),
	CONSTRAINT FK_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
)
GO
CREATE TABLE PHIEUNHAP
(
	SoPN INT IDENTITY(1,1),
	MaCH INT,
	NgayLapPN DATE,
	PRIMARY KEY (SoPN),
	CONSTRAINT FK_PN FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH)
)
GO
CREATE TABLE PHIEUXUAT
(
	SoPX INT IDENTITY(1,1),
	MaCH INT,
	NgayLapPX DATE,
	PRIMARY KEY (SoPX),
	CONSTRAINT FK_PX FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH)
)
GO
CREATE TABLE CT_PHIEUNHAP
(
	SoPN INT NOT NULL,
	MaNL INT NOT NULL,
	SoLuongNhap INT,
	PRIMARY KEY (SoPN, MaNL),
	CONSTRAINT FK_CTPN1 FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
	CONSTRAINT FK_CTPN2 FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
)
GO
CREATE TABLE CT_PHIEUXUAT
(
	SoPX INT NOT NULL,
	MaNL INT NOT NULL,
	SoLuongXuat INT,
	PRIMARY KEY (SoPX, MaNL),
	CONSTRAINT FK_CTPX1 FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
	CONSTRAINT FK_CTPX2 FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
)


	