USE [master]
GO

DROP DATABASE IF EXISTS [HOAYEUTHUONG]
GO
CREATE DATABASE [HOAYEUTHUONG]
GO
USE [HOAYEUTHUONG]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


DROP TABLE IF EXISTS [dbo].[DS_PHANLOAI];
DROP TABLE IF EXISTS [dbo].[SANPHAM];
DROP TABLE IF EXISTS [dbo].[NGUYENLIEU];
DROP TABLE IF EXISTS [dbo].[SANPHAM_CHUDE];
DROP TABLE IF EXISTS [dbo].[SANPHAM_NGUYENLIEU];

DROP TABLE IF EXISTS [dbo].[CUAHANG];
DROP TABLE IF EXISTS [dbo].[NHACUNGCAP];
DROP TABLE IF EXISTS [dbo].[SOLUONG_CH];
DROP TABLE IF EXISTS [dbo].[DS_CUNGCAP];

DROP TABLE IF EXISTS [dbo].[KHACHHANG];
DROP TABLE IF EXISTS [dbo].[NHANVIEN];
DROP TABLE IF EXISTS [dbo].[PHIEUCHAMCONG];
DROP TABLE IF EXISTS [dbo].[PHIEULUONG];

DROP TABLE IF EXISTS [dbo].[VOUCHER];
DROP TABLE IF EXISTS [dbo].[HOADON];
DROP TABLE IF EXISTS [dbo].[HOADON_VANCHUYEN];
DROP TABLE IF EXISTS [dbo].[PHIEUNHAP];
DROP TABLE IF EXISTS [dbo].[PHIEUXUAT];
DROP TABLE IF EXISTS [dbo].[PHIEUMUA];
DROP TABLE IF EXISTS [dbo].[CT_HOADON];
DROP TABLE IF EXISTS [dbo].[CT_PHIEUNHAP];
DROP TABLE IF EXISTS [dbo].[CT_PHIEUXUAT];
DROP TABLE IF EXISTS [dbo].[CT_PHIEUMUA];
GO

/*==============================================================*/
/* Groupe: Sanpham, nguyenlieu                                  */
/*==============================================================*/
CREATE TABLE [dbo].[DS_PHANLOAI](
	MaSo			INT					NOT NULL	IDENTITY(1,1),
	Loai			VARCHAR(20)			NOT NULL,
	UNIQUE (MaSo, Loai),
	CONSTRAINT PK_PHANLOAI PRIMARY KEY(MaSo)
);

CREATE TABLE [dbo].[SANPHAM](
	MaSP			INT				NOT NULL,
	Loai			VARCHAR(20)		NOT NULL,
	TenSP			NVARCHAR(50)	NOT NULL,
	NgaySangTao		DATE,
	DonGiaSP		DECIMAL(19,4)	DEFAULT(0),
	GiamGiaSP		DECIMAL(19,4)	DEFAULT(0),
	ThongTinSP		NVARCHAR(255),
	TinhTrangSP		NVARCHAR(50)	DEFAULT(N'Còn hàng'),
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MaSP),
	CONSTRAINT FK_SANPHAM_PHANLOAI FOREIGN KEY(MaSP, Loai) REFERENCES DS_PHANLOAI(MaSo, Loai)
);

CREATE TABLE [dbo].[NGUYENLIEU] (
	MaNL			INT				NOT NULL,
	Loai			VARCHAR(20)		NOT NULL,
	TenNL			NVARCHAR(50)	NOT NULL,
	YNghia			NVARCHAR(MAX),
	DonViTinh		NVARCHAR(10),
	DonGiaNL		DECIMAL(19,4)	DEFAULT(0),
	SoLuongKHO		INT				DEFAULT(0),
	SoLuongToiThieu INT				DEFAULT(0),
	CONSTRAINT PK_NGUYENLIEU PRIMARY KEY(MaNL),
	CONSTRAINT FK_NGUYENLIEU_PHANLOAI FOREIGN KEY(MaNL, Loai) REFERENCES DS_PHANLOAI(MaSo, Loai)
);

CREATE TABLE [dbo].[SANPHAM_CHUDE](
	MaSP			INT				NOT NULL,
	ChuDe			NVARCHAR(20)	NOT NULL,
	LoaiChuDe		NVARCHAR(20)	NOT NULL,
	TenSP			NVARCHAR(50),
	CONSTRAINT PK_CHUDE PRIMARY KEY(MaSP, ChuDe, LoaiChuDe),
	CONSTRAINT FK_CHUDE_SANPHAM FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE [dbo].[SANPHAM_NGUYENLIEU] (
	MaSP			INT				NOT NULL,
	MaNL			INT				NOT NULL,
	SoLuongNL		DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_SPNL PRIMARY KEY(MaSP, MaNL),
	CONSTRAINT FK_SPNL_SANPHAM FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP),
	CONSTRAINT FK_SPNL_NGUYENLIEU FOREIGN KEY(MaNL) REFERENCES NGUYENLIEU(MaNL)
);

/*==============================================================*/
/* Group: Dia diem	                                            */
/*==============================================================*/
CREATE TABLE [dbo].[CUAHANG] (
	MaCH			INT				NOT NULL	IDENTITY(1,1),
	TenCH			NVARCHAR(50)	NOT NULL,
	SdtCH			CHAR(10),
	DiaChiCH		NVARCHAR(MAX),
	ChuThichCH		NVARCHAR(MAX),
	CONSTRAINT PK_CUAHANG PRIMARY KEY(MaCH)
);

CREATE TABLE [dbo].[NHACUNGCAP](
	MaNCC			INT				NOT NULL	IDENTITY(1,1),
	TenNCC			NVARCHAR(50)	NOT NULL,
	SdtNCC			CHAR(10),
	DiaChiNCC		NVARCHAR(MAX),
	ChuThichNCC		NVARCHAR(MAX),
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MaNCC)
);

CREATE TABLE [dbo].[SOLUONG_NL] (
	MaCH			INT				NOT NULL,
	MaNL			INT				NOT NULL,
	SoLuongCH		INT				DEFAULT(0),
	CONSTRAINT PK_SLNL PRIMARY KEY(MaCH, MaNL),
	CONSTRAINT FK_SLNL_CUAHANG FOREIGN KEY(MaCH) REFERENCES CUAHANG(MaCH),
	CONSTRAINT FK_SLNL_NGUYENLIEU FOREIGN KEY(MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE [dbo].[DS_CUNGCAP](
	MaNCC			INT				NOT NULL,
	MaSo			INT				NOT NULL,
	Loai			VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_CUNGCAP PRIMARY KEY(MaNCC, MaSo),
	CONSTRAINT FK_CUNGCAP_NCC FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC),
	CONSTRAINT FK_CUNGCAP_SANPHAM FOREIGN KEY(MaSo, Loai) REFERENCES DS_PHANLOAI(MaSo, Loai)
);

/*==============================================================*/
/* Group: Nhan su	                                            */
/*==============================================================*/
CREATE TABLE [dbo].[KHACHHANG](
	MaKH			INT				NOT NULL	IDENTITY(1,1),
	TenKH			NVARCHAR(50)	NOT NULL,
	SdtKH			CHAR(10),
	DiaChiKH		NVARCHAR(MAX),
	EmaiKH			VARCHAR(MAX)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MaKH)
);

CREATE TABLE [dbo].[NHANVIEN](
	MaNV			INT				NOT NULL	IDENTITY(1,1),
	TenNV			NVARCHAR(50)	NOT NULL,
	LoaiNV			NVARCHAR(40),
	SdtNV			CHAR(10),
	DiaChiNV		NVARCHAR(MAX),
	EmailNV			VARCHAR(MAX),
	LuongCoDinh		DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);

CREATE TABLE [dbo].[PHIEUCHAMCONG](
	MaNV			INT				NOT NULL,
	NgayCham		DATE			NOT NULL,
	GioCham			TIME(7)			NOT NULL,
	CONSTRAINT PK_PCC PRIMARY KEY(MaNV, NgayCham, GioCham),
	CONSTRAINT FK_PCC_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE [dbo].[PHIEULUONG](
	MaNV			INT				NOT NULL,
	NgayNhan		DATE			NOT NULL,
	Luong			DECIMAL(19,4)	DEFAULT(0),
	Thuong			DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_PLUONG PRIMARY KEY(MaNV, NgayNhan),
	CONSTRAINT FK_PLUONG_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
);

/*==============================================================*/
/* Group: Cac loai Phieu                                        */
/*==============================================================*/
CREATE TABLE [dbo].[VOUCHER](
	MaVoucher		CHAR(10)		NOT NULL,	--manual
	GiaTri			DECIMAL(3, 2)	NOT NULL,
	HanSuDung		DATE,
	SoLanSuDung		INT				DEFAULT(1),
	CONSTRAINT PK_VOUCHER PRIMARY KEY(MaVoucher)
);

CREATE TABLE [dbo].[HOADON](
	MaHD			INT				NOT NULL	IDENTITY(1,1),
	MaCH			INT				NOT NULL,
	MaNV			INT				NOT NULL,
	MaKHGui			INT				NOT NULL,
	MaVoucher		CHAR(10),
	TongTien		DECIMAL(19,4)	DEFAULT(0),
	HinhThucTToan	NVARCHAR(50)	DEFAULT(N'COD'),
	TinhTrangTToan	NVARCHAR(50)	DEFAULT(N'Chưa thanh toán'),
	TinhTrangHD		NVARCHAR(50)	DEFAULT(N'Chưa xác nhận'),
	CONSTRAINT PK_HOADON PRIMARY KEY(MaHD),
	CONSTRAINT FK_HOADON_CUAHANG FOREIGN KEY(MaCH) REFERENCES CUAHANG(MaCH),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV),
	CONSTRAINT FK_HOADON_KHGui FOREIGN KEY(MaKHGui) REFERENCES KHACHHANG(MaKH),
	CONSTRAINT FK_HOADON_VOUCHER FOREIGN KEY(MaVoucher) REFERENCES VOUCHER(MaVoucher)
);

CREATE TABLE [dbo].[HOADON_VANCHUYEN](
	MaHD			INT				NOT NULL,
	MaKHNhan		INT,
	DiaChiNhan		NVARCHAR(MAX),
	ThoiGianGiao	DATE,
	LoiNhan			NVARCHAR(MAX),
	PhiVanChuyen	DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_HDVANCHUYEN PRIMARY KEY(MaHD),
	CONSTRAINT FK_HDVANCHUYEN FOREIGN KEY(MaHD) REFERENCES HOADON(MaHD),
	CONSTRAINT FK_HDVANCHUYEN_KHNhan FOREIGN KEY(MaKHNhan) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE [dbo].[PHIEUNHAP] (
	SoPN			INT				NOT NULL	IDENTITY(1,1),
	MaCH			INT				NOT NULL,
	NgayLapPN		DATE			NOT NULL,
	CONSTRAINT PK_PNHAP PRIMARY KEY(SoPN),
	CONSTRAINT FK_PNHAP_CH FOREIGN KEY(MaCH) REFERENCES CUAHANG(MaCH)
);

CREATE TABLE [dbo].[PHIEUXUAT] (
	SoPX			INT				NOT NULL	IDENTITY(1,1),
	MaCH			INT				NOT NULL,
	NgayLapPX		DATE			NOT NULL,
	CONSTRAINT PK_PXUAT PRIMARY KEY(SoPX),
	CONSTRAINT FK_PXUAT_CH FOREIGN KEY(MaCH) REFERENCES CUAHANG(MaCH)
);

CREATE TABLE [dbo].[PHIEUMUA](
	SoPM			INT				NOT NULL	IDENTITY(1,1),
	MaNCC			INT				NOT NULL,
	MaCH			INT,
	NgayLapPM		DATE			NOT NULL,
	TinhTrangGiao	NVARCHAR(50)	DEFAULT(N'Chưa giao'),
	TongChiPhi		DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_PMUA PRIMARY KEY(SoPM),
	CONSTRAINT FK_PMUA_NCC FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC),
	CONSTRAINT FK_PMUA_CH FOREIGN KEY(MaCH) REFERENCES CUAHANG(MaCH)
);

CREATE TABLE [dbo].[CT_HOADON](
	MaHD			INT				NOT NULL,
	MaSP			INT				NOT NULL,
	SoLuong			INT				DEFAULT(0),
	ThanhTien		DECIMAL(19,4)	DEFAULT(0),
	CONSTRAINT PK_CTHD PRIMARY KEY(MaHD, MaSP),
	CONSTRAINT FK_CTHD FOREIGN KEY(MaHD) REFERENCES HOADON([MaHD]),
	CONSTRAINT FK_CTHD_SP FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE [dbo].[CT_PHIEUNHAP] (
	SoPN			INT				NOT NULL,
	MaNL			INT				NOT NULL,
	SoLuongNhap		INT				DEFAULT(0),
	CONSTRAINT PK_CTPN PRIMARY KEY (SoPN, MaNL),
	CONSTRAINT FK_CTPN FOREIGN KEY(SoPN) REFERENCES PHIEUNHAP(SoPN),
	CONSTRAINT FK_CTPN_NL FOREIGN KEY(MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE [dbo].[CT_PHIEUXUAT] (
	SoPX			INT				NOT NULL,
	MaNL			INT				NOT NULL,
	SoLuongXuat		INT				DEFAULT(0),
	CONSTRAINT PK_CTPX PRIMARY KEY(SoPX, MaNL),
	CONSTRAINT FK_CTPX FOREIGN KEY(SoPX) REFERENCES PHIEUXUAT(SoPX),
	CONSTRAINT FK_CTPX_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE [dbo].[CT_PHIEUMUA](
	SoPM			INT				NOT NULL,
	MaSo			INT				NOT NULL,
	Loai			VARCHAR(20)		NOT NULL, 
	SoLuongMua		INT				DEFAULT(0),
	CONSTRAINT PK_CTPM PRIMARY KEY(SoPM, MaSo, Loai),
	CONSTRAINT FK_CTPM FOREIGN KEY(SoPM) REFERENCES PHIEUMUA(SoPM),
	CONSTRAINT FK_CTPM_SP FOREIGN KEY(MaSo, Loai) REFERENCES DS_PHANLOAI(MaSo, Loai)
);
GO





/*==============================================================*/
/* Trigger                                                      */
/*==============================================================*/
CREATE OR ALTER TRIGGER [dbo].[ChuDe_TenSP]
ON [dbo].[SANPHAM_CHUDE]
INSTEAD OF  INSERT
AS
BEGIN
	INSERT INTO [dbo].[SANPHAM_CHUDE](MaSP, ChuDe, LoaiChuDe, TenSP)
	SELECT i.MaSP, i.ChuDe, i.LoaiChuDe,
		CASE WHEN i.TenSP IS NOT NULL THEN i.TenSP 
			ELSE (SELECT sp.TenSP FROM SANPHAM sp WHERE sp.MaSP = i.MaSP)END
	FROM inserted i
END
GO
ALTER TABLE [dbo].[SANPHAM_CHUDE] ENABLE TRIGGER ChuDe_TenSP
GO



