USE [HOAYEUTHUONG]
GO

-- == Xóa tất cả dữ liệu trong bảng ==
-- disable all triggers
EXEC sp_MSForEachTable 'DISABLE TRIGGER ALL ON ?'

-- disable all constraints
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'

-- delete data in all tables
EXEC sp_MSforeachtable 'SET QUOTED_IDENTIFIER ON; DELETE FROM ?'

-- enable all constraints
EXEC sp_MSForEachTable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'

-- enable all triggers
EXEC sp_MSForEachTable 'ENABLE TRIGGER ALL ON ?'
GO

--reset IDENTITY VALUE
DBCC CHECKIDENT([DS_PHANLOAI], RESEED, 0)
DBCC CHECKIDENT([CUAHANG], RESEED, 0)
DBCC CHECKIDENT([NHACUNGCAP], RESEED, 0)
DBCC CHECKIDENT([KHACHHANG], RESEED, 0)
DBCC CHECKIDENT([NHANVIEN], RESEED, 0)

DBCC CHECKIDENT([HOADON], RESEED, 0)
DBCC CHECKIDENT([PHIEUNHAP], RESEED, 0)
DBCC CHECKIDENT([PHIEUXUAT], RESEED, 0)
DBCC CHECKIDENT([PHIEUMUA], RESEED, 0)
GO