USE [HOAYEUTHUONG]
GO
EXEC sp_addLogin 'LGQuanly','qly'
EXEC sp_addLogin 'LGQuantri','qtri'
GO
CREATE USER userQL FOR LOGIN LGQuanly
CREATE USER userQT FOR LOGIN LGQuantri
GO
EXEC sp_addrole 'QuanLy'
EXEC sp_addrole 'QuanTri'
GO
EXEC sp_addrolemember 'QuanLy', 'userQL'
EXEC sp_addrolemember 'QuanTri', 'userQT'
GO

GRANT ALL ON SANPHAM TO QuanTri
GRANT ALL ON DS_CUNGCAP TO QuanTri
GRANT ALL ON DS_PHANLOAI TO QuanTri
GRANT SELECT ON NHACUNGCAP TO QuanTri
GRANT ALL ON NGUYENLIEU TO QuanTri
GRANT ALL ON SANPHAM_CHUDE TO QuanTri
GRANT ALL ON SANPHAM_NGUYENLIEU TO QuanTri
GRANT ALL ON SOLUONG_NL TO QuanTri
GRANT SELECT ON VOUCHER TO QuanTri
GRANT ALL ON PHIEUNHAP TO QuanTri
GRANT ALL ON PHIEUMUA TO QuanTri
GRANT ALL ON PHIEUXUAT TO QuanTri
GRANT ALL ON CT_PHIEUMUA TO QuanTri
GRANT ALL ON CT_PHIEUNHAP TO QuanTri
GRANT ALL ON CT_PHIEUXUAT TO QuanTri
GRANT SELECT ON CUAHANG TO QuanTri
GRANT SELECT ON NHANVIEN TO QuanTri
GRANT SELECT ON HOADON TO QuanTri
GRANT SELECT ON CT_HOADON TO QuanTri
GRANT SELECT ON HOADON_VANCHUYEN TO QuanTri
GO
EXEC sp_addsrvrolemember 'QuanLy', 'sysadmin';

