USE [HOAYEUTHUONG]
GO
--TÌM KIẾM SP
CREATE OR ALTER PROCEDURE TIMKIEMSP @MASP INT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SANPHAM WHERE MASP = @MASP)
	BEGIN
		PRINT N'Sản phẩm hiện không tồn tại'
		RETURN
	END

	SELECT *
	FROM SANPHAM
	WHERE MASP = @MASP
END
GO
EXEC TIMKIEMSP 10000
--ĐẶT HÀNG
GO
CREATE OR ALTER PROCEDURE THEMVAOGIOHANG @MAKH INT, @MAHD INT, @MASP INT, @SL INT, @VOUCHER CHAR(10)
AS
BEGIN
	IF @MAHD IS NULL
	BEGIN
		INSERT HOADON(MaKHGui,MaVoucher) VALUES (@MAKH, @VOUCHER)
		SET @MaHD = SCOPE_IDENTITY()
		INSERT CT_HOADON(MaHD,MaSP,SoLuong) VALUES (@MaHD, @MASP, @SL)
	END
	ELSE 
	BEGIN
		IF NOT EXISTS (SELECT * FROM HOADON WHERE MAHD = @MAHD AND MaKHGui = @MAKH)
		BEGIN
			PRINT N'Hóa đơn này không phải của bạn'
			RETURN
		END
		INSERT CT_HOADON(MaHD,MaSP,SoLuong) VALUES (@MAHD, @MASP, @SL)
	END
END
GO
EXEC THEMVAOGIOHANG 4439, 1, 10001, 3, NULL
GO
--Thanh toán

--Cần sửa lại cái họ tên cho phép NULL vì khách hàng nhận có thể NULL
CREATE OR ALTER PROCEDURE THANHTOAN @MAHD INT, 
									@HINHTHUCTT NVARCHAR(50), 
									--THÔNG TIN NGƯỜI NHẬN
									@HOTENNGUOINHAN NVARCHAR(50),
									@SDTNGNHAN CHAR(10),
									@DIACHI NVARCHAR(MAX),
									@EMAIL NVARCHAR(MAX),
									@THOIGIANGIAO DATE,
									@LOINHAN NVARCHAR(MAX)
AS
BEGIN TRAN
	--Cập nhật TTHĐ
	UPDATE HOADON SET HinhThucTToan = @HINHTHUCTT, TinhTrangTToan = N'Đã thanh toán', TinhTrangHD = N'Đã xác nhận' WHERE MAHD = @MAHD
	
	--Kiểm tra và trừ số lần sử dụng Voucher
	DECLARE @VOUCHER INT
	SET @VOUCHER = (SELECT MaVoucher FROM HOADON WHERE MAHD = @MAHD)
	IF @VOUCHER IS NOT NULL
	BEGIN
		UPDATE VOUCHER
		SET SoLanSuDung = SoLanSuDung - 1
		WHERE MaVoucher = @VOUCHER
	END

	INSERT KHACHHANG(TenKH,SdtKH,DiaChiKH,EmailKH) VALUES (@HOTENNGUOINHAN, @SDTNGNHAN, @DIACHI, @EMAIL)
	DECLARE @MaKHNhan INT
	SET @MaKHNhan = SCOPE_IDENTITY()

	INSERT HOADON_VANCHUYEN(MaHD,MaKHNhan, DiaChiNhan, ThoiGianGiao, LoiNhan) VALUES (@MAHD, @MaKHNhan, @DIACHI, @THOIGIANGIAO, @LOINHAN)
COMMIT TRAN
GO
EXEC THANHTOAN 1, N'COD', N'Phạm Hồng Quân', '0912188212', N'Buôn Ma Thuột', NULL, '2021-12-17', NULL