USE [HOAYEUTHUONG]
GO

--Thêm Chủ đề cho SP
CREATE OR ALTER PROC THEM_CHUDE @MaSP INT,
								@ChuDe AS NVARCHAR(20),
								@ChuDe_2 AS NVARCHAR(20) = NULL
AS
BEGIN
	INSERT SANPHAM_CHUDE(MaSP, ChuDe, LoaiChuDe)
	VALUES (@MaSP, @ChuDe, @ChuDe_2)
END							
GO

--Thêm SP
CREATE OR ALTER PROCEDURE THEMSP @LOAI VARCHAR(20), 
								 @TENSP NVARCHAR(50), 
								 @NGAYST DATE, 
								 @GIASP DECIMAL(19,4),
								 @GIAMGIA DECIMAL(19,4),
								 @TTINSP NVARCHAR(255),
								 @TTSP NVARCHAR(50),
								 @ChuDe AS NVARCHAR(20) = NULL,
								 @ChuDe_2 AS NVARCHAR(20) = NULL
AS
BEGIN
	INSERT INTO SANPHAM(Loai, TenSP, NgaySangTao, DonGiaSP, GiamGiaSP, ThongTinSP, TinhTrangSP) 
	VALUES (@LOAI, @TENSP, @NGAYST, @GIASP, @GIAMGIA, @TTINSP, @TTSP)

	DECLARE @MaSP INT = SCOPE_IDENTITY()

	IF (@ChuDe IS NOT NULL)
	BEGIN
		INSERT SANPHAM_CHUDE(MaSP, ChuDe, LoaiChuDe)
		VALUES (@MaSP, @ChuDe, @ChuDe_2)
	END
END
GO


--Xóa SP
CREATE OR ALTER PROCEDURE XOA_SP @MASP INT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SANPHAM WHERE MASP = @MASP)
	BEGIN
		PRINT N'Sản phẩm không tồn tại'
		RETURN
	END
	--DELETE SANPHAM WHERE MASP = @MASP   --không xóa (status atri)
	UPDATE SANPHAM SET TinhTrangSP = N'Hết hàng' WHERE MASP = @MASP
END
GO