USE [HOAYEUTHUONG]
GO

--Tạo voucher
CREATE OR ALTER PROCEDURE THEMVOUCHER_GIAMGIA @MAVC CHAR(10), @GTRI DECIMAL(3,2), @HSD DATE, @SL INT
AS
BEGIN
	IF NOT EXISTS (SELECT MaVoucher FROM VOUCHER WHERE MaVoucher = @MAVC)
	BEGIN 
		INSERT INTO VOUCHER(MaVoucher, GiaTri, HanSuDung, SoLanSuDung) VALUES (@MAVC, @GTRI, @HSD, @SL) 
		RETURN
	END
	UPDATE VOUCHER
	SET GiaTri = @GTRI, HanSuDung = @HSD, SoLanSuDung = @SL
	WHERE MaVoucher = @MAVC
END
GO

--Thống kê các mặt hàng bán chạy
CREATE OR ALTER PROCEDURE THONGKEBANCHAY 
AS
BEGIN
	SELECT TOP(10) CT.MaSP, SP.TenSP, SUM(CT.SoLuong) AS SL
	FROM CT_HOADON CT JOIN SANPHAM SP ON SP.MaSP = CT.MaSP
	GROUP BY CT.MaSP, SP.TenSP
	ORDER BY SUM(CT.SoLuong) DESC
END
GO
EXEC THONGKEBANCHAY
GO

--Thống kê các mặt hàng bán chậm
CREATE OR ALTER PROCEDURE THONGKEBANCHAM
AS
BEGIN
	SELECT TOP(10) CT.MaSP, SP.TenSP, SUM(CT.SoLuong) AS SL
	FROM CT_HOADON CT JOIN SANPHAM SP ON SP.MaSP = CT.MaSP
	GROUP BY CT.MaSP, SP.TenSP
	ORDER BY SUM(CT.SoLuong) ASC
END
GO
EXEC THONGKEBANCHAM
GO

--Thống kê doanh thu cao nhất
CREATE OR ALTER PROC THONGKEDOANHTHU
AS
BEGIN
	SELECT HD.MaCH, CH.TenCH, SUM(HD.TongTien) AS 'Doanh thu'
	FROM CUAHANG CH JOIN HOADON HD ON CH.MaCH = HD.MaCH AND HD.TinhTrangHD = N'Đã thanh toán'
	GROUP BY HD.MaCH, CH.TenCH
	ORDER BY SUM(HD.TongTien) DESC
END