USE [HOAYEUTHUONG]
GO
--Thêm SP
CREATE OR ALTER PROCEDURE THEMSP @LOAI VARCHAR(20), 
								 @TENSP NVARCHAR(50), 
								 @NGAYST DATE, 
								 @GIASP DECIMAL(19,4),
								 @GIAMGIA DECIMAL(19,4),
								 @TTINSP NVARCHAR(255),
								 @TTSP NVARCHAR(50)
AS
BEGIN
	INSERT INTO SANPHAM(Loai, TenSP, NgaySangTao, DonGiaSP, GiamGiaSP, ThongTinSP, TinhTrangSP) 
	VALUES (@LOAI, @TENSP, @NGAYST, @GIASP, @GIAMGIA, @TTINSP, @TTSP)
END
GO
EXEC THEMSP 'SP_Mua', N'Hoa mừng SN', NULL, 19000, 0, NULL, N'Còn hàng'
--Xóa SP
GO
CREATE OR ALTER PROCEDURE XOA_SP @MASP INT
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM SANPHAM WHERE MASP = @MASP)
	BEGIN
		PRINT N'Sản phẩm không tồn tại'
		RETURN
	END
	DELETE SANPHAM WHERE MASP = @MASP
END
GO
EXEC XOA_SP 17052