USE [HOAYEUTHUONG]
GO
--Tạo voucher
CREATE OR ALTER PROCEDURE THEMVOUCHER_GIAMGIA @MAVC CHAR(10), @GTRI DECIMAL(3,2), @HSD DATE, @SL INT
AS
BEGIN
	INSERT INTO VOUCHER VALUES (@MAVC, @GTRI, @HSD, @SL)
END
GO
--Thống kê các mặt hàng bán chạy
CREATE OR ALTER PROCEDURE THONGKEBANCHAY 
AS
BEGIN
	SELECT TOP(10) CT.MaSP, SP.TenSP, SUM(CT.SoLuong) AS SL
	FROM CT_HOADON CT, SANPHAM SP
	WHERE CT.MaSP = SP.MaSP
	GROUP BY CT.MaSP, SP.TenSP
	ORDER BY SUM(CT.SoLuong) DESC
END
GO
EXEC THONGKEBANCHAY
GO
--Thống kê các mặt hàng bán chậm
CREATE OR ALTER PROCEDURE THONGKEBANCHAM
AS
BEGIN
	SELECT TOP(10) CT.MaSP, SP.TenSP, SUM(CT.SoLuong) AS SL
	FROM CT_HOADON CT, SANPHAM SP
	WHERE CT.MaSP = SP.MaSP
	GROUP BY CT.MaSP, SP.TenSP
	ORDER BY SUM(CT.SoLuong) ASC
END
GO
EXEC THONGKEBANCHAM
--Thống kê doanh thu cao nhất
SELECT HD.MaCH, CH.TenCH, SUM(HD.TongTien) AS 'Doanh thu'
FROM HOADON HD, CUAHANG CH
WHERE CH.MaCH = HD.MaCH AND HD.TinhTrangHD = N'Đã thanh toán'
GROUP BY HD.MaCH, CH.TenCH
ORDER BY SUM(HD.TongTien) DESC